name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened ]


env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - run: rustup update
    - run: cargo build --release
