name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - run: rustup update
    - run: cargo build --verbose
    - run: cargo test --verbose
